version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep [m]ysqld_safe"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yallo/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yallo/data/mariadb'