; Activer ou désactiver l'environnement de nettoyage
clear_env = no

; Section pour la configuration des pools PHP-FPM (généralement dans un fichier `www.conf`)
[www]
; Définir l'adresse et le port d'écoute pour PHP-FPM
listen = wordpress:9000  ; Utilise un conteneur Docker nommé "wordpress" comme hôte et le port 9000

; Autres paramètres du pool
listen.mode = 0660
listen.owner = www-data
listen.group = www-data

; Définit la taille du cache
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Paramètres pour les logs
error_log = /var/log/php-fpm.log
log_level = notice

; Définit le nombre maximal de processus enfants
pm.max_requests = 500

; Timeout de requête
request_terminate_timeout = 30s

; Gestion de l'utilisateur et du groupe
user = www-data
group = www-data
